### ISSUE TITLE
Roact.brs files call different component functions.

### ISSUE THREAD

**Issue by lukechinworth** [briandunnington/Roact#4]
* `./Roact.brs` calls non-prefixed component functions, e.g. "conditionalRender".
* `./samples/tictactoe/source/Roact.brs` calls prefixed component functions, e.g. "roactConditionalRender".

It is confusing that there are two different versions of the `Roact.brs` file, so I think it would be best to remove one, maybe the root file because it does not have corresponding RoactComponent files.

Thanks for this lib!

**Comment by briandunnington** [comment]
Sorry for the confusion - you are right that the files in `samples` are the correct version. I removed the outdated file from the root.
