### ISSUE TITLE
Did this ever get used for any projects?

### ISSUE THREAD

**Issue by jfrux** [briandunnington/Roact#5]
Curious of a post mortem if any...?

**Comment by briandunnington** [comment]
I changed companies/jobs and no longer do any Roku development, so I personally never shipped a production app using this framework. I did create several non-trivial apps with it on my own, and I have heard from other folks that have used it, but dont have any first-hand experience of using it with a dev team to ship an app.

For my personal projects, I actually ended up really liking this pattern. It has some learning curve and feels a little strange if you have done a lot of BrightScript work, but if you have dont a lot of React dev, then it feels pretty natural. I was able to create apps much faster than before, and I liked the simplified way to reason about how the apps worked (especially when combined with Redoku for state management).
